// <auto-generated />
namespace Kauffman.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SubscriptionData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubscriptionData));
        
        string IMigrationMetadata.Id
        {
            get { return "201802150831375_SubscriptionData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
