// <auto-generated />
namespace Kauffman.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _14feb2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14feb2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140924567_14feb2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
